### ISSUE TITLE
[BUG] Unable to run AI experiments for Time-Series problems

### ISSUE THREAD

**Issue by Chandra-Ananthapatnayakuni** [dxc-technology/DXC-Industrialized-AI-Starter#87]
**Describe the bug**
I am unable to run AI experiments for Time-Series problems

**To Reproduce**
When I passed **timeseries** as a parameter, I got an error as below:

![image](https://user-images.githubusercontent.com/29919236/107557030-1a7a7e80-6bff-11eb-8376-eb500866ad27.png)

I tried to pick up an example from https://nbviewer.jupyter.org/github/dxc-technology/DXC-Industrialized-AI-Starter/blob/c58754247060262ac0949396e48f71861cb79d4e/Examples/Time_series_Model.ipynb

on setting the value : **"model": 'timeseries'**,
The timeseries values are not displaying as expected. Instead it shows the same value for all predictions
 
Please let me a way to handle timeseries problems

**Expected behavior**
Please create a function for Time-Series problem. Please revoke the functionality. As it looks like, it was already implemented

**Screenshots**
Added the images

**Additional context**

**Comment by karthikreddykuna** [comment]
@Chandra-Ananthapatnayakuni Please try using 'timeseries' only instead of 'ai.timeseries'. Let us know if you still face the issue. If you are able to execute successfully please close the issue.

**Comment by Chandra-Ananthapatnayakuni** [comment]
@karthikreddykuna as I mentioned in this issue, Yesterday, the model was giving me same set of predicted values when I passed the value "model": 'timeseries',
It looks like the problem is fixed now. 

The accuracy seems to be a problem
Can I try other timeseries problems such as ARIMA, ARMA and others. Are there any examples around it?

**Comment by karthikreddykuna** [comment]
@Chandra-Ananthapatnayakuni 
The time series models that are available in the AI_Starter library are
- Auto-Regressive model
- Simple exponential smoothing model
- Double exponential smoothing model
- ARIMA model

The best model will be selected automatically based on the RMSE value. If you want to explore the performance of any other time-series model or at the individual level. We suggest you please build your custom model instead of using the run_experiment function in AI_Starter.

**Comment by karthikreddykuna** [comment]
Closing the issue as a suitable resolution was suggested. Please raise a new request if you have any other queries.
